version: "3.9"

services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: .docker/next/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next:/app:delegated
      - /app/node_modules
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - mongo

  nestjs:
    container_name: nestjs
    build:
      context: .
      dockerfile: .docker/nest/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - ./nest:/app
      - /app/node_modules
    command: npm run start:prod
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nextjs
      - nestjs
      - mongo

volumes:
  mongo-data:
